const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnJump
	];
};
self.C3_JsPropNameTable = [
	{BackgroundTile: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Solid: 0},
	{SolidTile: 0},
	{Sine: 0},
	{MovingSolidTile: 0},
	{Jumpthru: 0},
	{JumpThruTile: 0},
	{Keyboard: 0},
	{Text: 0},
	{Switch: 0},
	{Sprite: 0},
	{MovingSolidTile2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Bullet: 0},
	{TiledBackground: 0},
	{Sprite4: 0}
];

self.InstanceType = {
	BackgroundTile: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	SolidTile: class extends self.ITiledBackgroundInstance {},
	MovingSolidTile: class extends self.ITiledBackgroundInstance {},
	JumpThruTile: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MovingSolidTile2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {}
}